CREATE TABLE event (
    eventid BIGINT(12) NOT NULL UNIQUE,
    year INT(4),
    month INT,
    day INT,
    latitude FLOAT,
    longitude FLOAT,
    crit1 INT(1),
    crit2 INT(1),
    crit3 TEXT,
    dbsource TEXT,
    success INT,
    targetid INT,
    gid INT,
    fatalityid BIGINT,
    weaponid INT,
    attackid INT,
    PRIMARY KEY (eventid),
    FOREIGN KEY (targetid) REFERENCES target(targetid),
    FOREIGN KEY (gid) REFERENCES $db.group(gid),
    FOREIGN KEY (fatalityid) REFERENCES fatality(fatalityid),
    FOREIGN KEY (weaponid) REFERENCES weapon(weaponid),
    FOREIGN KEY (attackid) REFERENCES attack(attackid)
);