CREATE TABLE fatality(
    fatalityid BIGINT(15) NOT NULL UNIQUE,
    nkill INT,
    nkillus INT,
    nkillter INT,
    nwound INT,
    nwoundus INT,
    nwoundte INT,
    property INT,
    propextent INT,
    propextent_txt VARCHAR(20),
    propvalue INT,
    propcomment VARCHAR(15),
    ishostkid INT,
    nhostkid INT,
    nhostkidus INT,
    divert VARCHAR(15),
    kidhijcountry VARCHAR(20),
    ransom INT,
    ransomamt INT,
    ransomamtus INT,
    ransompaid INT,
    ransompaidus INT,
    ransomnote INT,
    hostkidoutcome INT,
    hostkidoutcome_txt VARCHAR(20),
    nreleased INT,
    PRIMARY KEY (fatalityid)
    ) ;