create table group(
gid INT NOT NULL UNIQUE,
gname VARCHAR(100) DEFAULT 'Unknown',	
gsubname VARCHAR(100) DEFAULT 'Unknown',	
gname2	VARCHAR(100) DEFAULT 'Unknown',
gsubname2 VARCHAR(100) DEFAULT 'Unknown',	
gname3	VARCHAR(100) DEFAULT 'Unknown',
gsubname3 VARCHAR(100) DEFAULT 'Unknown',	
guncertain1	INT,
guncertain2 INT,
guncertain3	INT,
individual	INT,
nperps	INT,
nperpcap INT,	
claimed	INT,
claimmode INT,	
claimmode_txt VARCHAR(100),	
claim2	INT,
claimmode2	INT,
claimmode2_txt	VARCHAR(100),
claim3	INT,
claimmode3	INT,
claimmode3_txt	VARCHAR(100),
compclaim VARCHAR(100),
Constraint g_pk Primary Key(gid)
);