CREATE TABLE target(
    targetid INT NOT NULL UNIQUE,
    targtype1 INT NOT NULL,
    targtype1_txt VARCHAR(100),
    targsubtype1 INT,	
    targsubtype1_txt VARCHAR(100),
    corp1 VARCHAR(100),
    target1 VARCHAR(100),
    natlty1 INT,
    natlty1_txt VARCHAR(100),
    targtype2 INT,
    targtype2_txt VARCHAR(100),
    targsubtype2 INT,
    targsubtype2_txt VARCHAR(100),
    corp2 TEXT,
    target2 TEXT,
    natlty2 INT,
    natlty2_txt TEXT,
    targtype3 INT,
    targtype3_txt TEXT,
    targsubtype3 INT,
    targsubtype3_txt TEXT,
    corp3 TEXT,
    target3 TEXT,
    natlty3 INT,
    natlty3_txt TEXT,
    countryid INT,
    regionid	INT,
    PRIMARY KEY (targetid),
    FOREIGN KEY (countryid) REFERENCES country(countryid),
    FOREIGN KEY (regionid) REFERENCES region(regionid)
);